#!/usr/bin/env bash
# tools-server/bootstrap.sh — idempotent provisioner for the mvp-pool tools server.
#
# Brings a Linux box (Ubuntu 24.04+ tested) into the desired state for hosting:
#   1) base hardening + UFW
#   2) Docker (container runtime)
#   3) build host (/srv/build, zstd, buildx, swap, weekly prune cron)
#   4) Xray VLESS+Reality VPN (port 2053 by default)
#   5) mvpool-dashboard (Bun + Hono on 127.0.0.1:3030)
#
# Usage (run as root, on the target server):
#   sudo bash bootstrap.sh                    # all modules
#   sudo bash bootstrap.sh 03 05              # only modules 03 and 05
#   sudo SKIP="04" bash bootstrap.sh          # all modules except 04
#
# Re-running is safe — every module detects existing state and skips work.
#
# Secrets persist in /root/.tools-server.env (mode 600). To migrate this
# server to a new VPS:
#   1. scp /root/.tools-server.env to the new VPS as /root/.tools-server.env
#   2. scp the entire tools-server/ tree to the new VPS as /srv/tools-server/
#      (or rsync from your laptop's mvp-pool checkout)
#   3. sudo bash /srv/tools-server/bootstrap.sh
#   4. import the existing client URI on phones unchanged

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "must run as root (try: sudo bash $0)" >&2
    exit 1
fi

HERE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
export TOOLS_SERVER_ROOT="$HERE"

# Pretty output
if [[ -t 1 ]]; then
    C_BLUE=$'\033[1;34m'; C_GREEN=$'\033[1;32m'; C_YELLOW=$'\033[1;33m'
    C_GREY=$'\033[0;37m'; C_RESET=$'\033[0m'
else
    C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_GREY=""; C_RESET=""
fi
banner() { printf '\n%s== %s ==%s\n' "$C_BLUE" "$*" "$C_RESET"; }
note()   { printf '%s   %s%s\n'      "$C_GREY" "$*" "$C_RESET"; }
ok()     { printf '%s   ok %s%s\n'   "$C_GREEN" "$*" "$C_RESET"; }
warn()   { printf '%s   ! %s%s\n'    "$C_YELLOW" "$*" "$C_RESET" >&2; }

# Load (or create) persistent config & secrets file
ENV_FILE=/root/.tools-server.env
if [[ ! -f "$ENV_FILE" ]]; then
    install -m 600 /dev/null "$ENV_FILE"
    cat > "$ENV_FILE" <<'EOF'
# tools-server runtime config. mode 600. Backup before destroying this server.
# Keys generated by modules on first run; safe to copy to a new VPS verbatim.
EOF
fi

# Auto-export every key=value loaded from the env file so the child bash
# processes that run each module inherit them (Reality keys, UUID, …).
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

# Inputs (env-overridable)
VPN_PORT="${VPN_PORT:-2053}"
VPN_SNI="${VPN_SNI:-www.cloudflare.com}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3030}"
BUILD_USER="${BUILD_USER:-ali}"
SERVER_PUBLIC_IP="${SERVER_PUBLIC_IP:-$(curl -fsS --max-time 4 https://api.ipify.org 2>/dev/null || echo 0.0.0.0)}"
SWAP_SIZE_GB="${SWAP_SIZE_GB:-2}"

export VPN_PORT VPN_SNI DASHBOARD_PORT BUILD_USER SERVER_PUBLIC_IP SWAP_SIZE_GB ENV_FILE

# Discover modules
mapfile -t ALL_MODULES < <(find "$HERE/modules" -maxdepth 1 -type f -name '[0-9]*.sh' | sort)
[[ ${#ALL_MODULES[@]} -gt 0 ]] || { echo "no modules in $HERE/modules"; exit 1; }

# Pick which to run
SKIP_LIST="${SKIP:-}"
if (( $# > 0 )); then
    declare -a PICKED=()
    for arg in "$@"; do
        for m in "${ALL_MODULES[@]}"; do
            base="$(basename "$m")"
            if [[ "$base" == ${arg}-*.sh ]]; then PICKED+=("$m"); fi
        done
    done
    [[ ${#PICKED[@]} -gt 0 ]] || { echo "no modules matched: $*"; exit 1; }
    MODULES=("${PICKED[@]}")
else
    MODULES=("${ALL_MODULES[@]}")
fi

banner "tools-server bootstrap"
note "host=$(hostname) ip=$SERVER_PUBLIC_IP user=$BUILD_USER"
note "vpn port=$VPN_PORT sni=$VPN_SNI · dashboard port=$DASHBOARD_PORT · swap=${SWAP_SIZE_GB}G"
note "env file=$ENV_FILE (mode 600)"
note "modules (${#MODULES[@]}): $(printf '%s ' "${MODULES[@]##*/}")"
[[ -n "$SKIP_LIST" ]] && note "skipping: $SKIP_LIST"

# Helper for modules: persist a key=value pair into ENV_FILE.
# Replaces any existing line for the same key.
_persist_env_var() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=${value//|/\\|}|" "$ENV_FILE"
    else
        printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
}
export -f _persist_env_var

for module in "${MODULES[@]}"; do
    base="$(basename "$module" .sh)"
    num="${base%%-*}"
    if [[ ",$SKIP_LIST," == *",$num,"* ]]; then
        warn "skip $base (in SKIP)"
        continue
    fi
    banner "module $base"
    bash "$module"
    ok   "$base done"
done

banner "bootstrap complete"
note "secrets: $ENV_FILE  (back this up to migrate the server with same VPN keys)"
note "verify:  systemctl status xray mvpool-dashboard --no-pager -l | head -20"
note "client:  cat /root/xray-vpn-credentials.txt    # client URI for Shadowrocket / v2rayNG"
note "tunnel:  ssh -fNL 8080:localhost:$DASHBOARD_PORT \$(hostname)   # then visit http://localhost:8080"
