# Per-MVP env. Lives at /srv/apps/<slug>/.env (mode 600).
# Generated by `mvpool mvp:add`; edit in place for app-specific vars.
# IMAGE_TAG is rewritten by `mvpool deploy` on every successful deploy.

NODE_ENV=production
LOG_LEVEL=info

# Identifies this MVP across the pool.
SLUG={{SLUG}}
DOMAIN={{DOMAIN}}

# Image coordinates. REGISTRY is the operator's self-hosted registry on the
# pool VPS (or another reachable registry). IMAGE_TAG tracks the currently
# deployed version; rolling back == setting it to a prior tag and `compose up`.
REGISTRY={{REGISTRY}}
IMAGE_TAG={{IMAGE_TAG}}

# Public URLs (proxied by shared Caddy)
PUBLIC_URL=https://{{DOMAIN}}
